GET http://localhost:3000/userapi/test

###
//request for user registration
POST http://localhost:3000/userapi/register
Content-Type: application/json

{
    "type":"user",
    "username":"user3",
    "email":"user3@gmail.com",
    "password":"user3"
}

###
//request for user login
POST http://localhost:3000/userapi/login
Content-Type: application/json

{
    "username":"user3",
    "password":"user3"
}